### ISSUE TITLE
"No forms found" , and  403 (Forbidden) and Could not connect to API server messages on the Formflow-Web UI login

### ISSUE THREAD

**Issue by nagannv** [AOT-Technologies/forms-flow-ai#548]
By taking the reference of docker deployment and OpenShift helm chart, we have created  deployment artifacts to deploy the form-flow application stack on OpenStack  kubernetes environment and exposed the application using ambassador loadbalancer. After keycloak authentication, we are able to can access web UIs of all the services in forms-flow stack, however, observing below issues om accessing the forms-flow webUI
 
**1. on accessing forms-flow webUI using formsflow-designer user account,**

 on the browser console log
```
GET https://formio.formflow.click/current 400 (Bad Request)
/formflow/62b2a334b8…124b5b4/view-edit:1 Uncaught (in promise) 
{status: 400, message: 'Could not connect to API server (Cast to ObjectId …ype string) at path "_id" for model "submission")', networkError: true}

```
and on the UI can see the default forms ( Freedom of Information and Protection of Privacy and New Business License Application), however, on trying to edit the form in the "Please select from one of the following workflows." drop-down getting NO Data message

**2. on accessing the forms-flow webUI using formsflow-reviewer or using formsflow-client account**

getting **No forms found** message on the UI, and no errors/messages in the browser console 

**3. on accessing forms-flow webUI formsflow-approver or using formsflow-clerk user accounts** 

```
Failed to load resource: the server responded with a status of 403 (Forbidden)
https://camunda.formflow.click/camunda/forms-flow-bpm-socket/info?accesstoken1656481567282 403 (Forbidden)
```

- formsflow.ai Version: 4.0.5
- Browser: Chrome
- Browser version: Version 102.0.5005.115 (Official Build) (64-bit)

**Additional information**

1. referred https://github.com/AOT-Technologies/forms-flow-ai/issues/106
2. sharing you the config parameters of the deployment

**forms-flow-web/templates/configmap.yaml**

```
        "NODE_ENV": "production",
        "REACT_APP_CLIENT_ROLE": "formsflow-client",
        "REACT_APP_STAFF_DESIGNER_ROLE": "formsflow-designer",
        "REACT_APP_STAFF_REVIEWER_ROLE": "formsflow-reviewer",,
        "REACT_APP_API_SERVER_URL": "https://formio.formflow.click",
        "REACT_APP_API_PROJECT_URL": "https://formio.formflow.click",
        "REACT_APP_CAMUNDA_API_URI": "https://camunda.formflow.click/camunda",
        "REACT_APP_KEYCLOAK_CLIENT": "forms-flow-web",
        "REACT_APP_USER_ACCESS_PERMISSIONS": {"accessAllowApplications":true,"accessAllowSubmissions":true},
        "REACT_APP_WEB_BASE_URL": "forms-flow-webapi", ---> k8s fomrs-flow API SVC
        "REACT_APP_INSIGHT_API_BASE": "forms-flow-analytics", ---> k8s analytics SVC
        "REACT_APP_KEYCLOAK_URL_REALM": "forms-flow-ai",
        "REACT_APP_KEYCLOAK_URL": "https://kc.formflow.click",
        "REACT_APP_APPLICATION_NAME": "formsflow.ai", 
```

NOTE: In the above and below configs,  tried changing k8s SVC with the respective service publicly resolvable URL,but, observing the same behavior, therefore tried using K8S SVC to avoid the CORS messages on the browser console.

**forms-flow-webapi/templates/deploymentconfig.yaml**
```
      - env:
        - name: DATABASE_URL
          value: "postgresql://postgres:<password>@forms-flow-webapi-postgresql:5432/webapi"
        - name: BPM_API_BASE
          value: "forms-flow-bpm"   ---> k8s BPM SVC
        - name: BPM_CLIENT_ID
          value: "forms-flow-bpm"
        - name: BPM_TOKEN_API
          value: "https://kc.formflow.click/auth/realms/forms-flow-ai/protocol/openid-connect/token"
        - name: JWT_OIDC_ALGORITHMS
          value: "RS256"
        - name: JWT_OIDC_AUDIENCE
          value: "forms-flow-web"
        - name: JWT_OIDC_CACHING_ENABLED
          value: "True"
        - name: JWT_OIDC_ISSUER
          value: "https://kc.formflow.click/auth/realms/forms-flow-ai"
        - name: JWT_OIDC_JWKS_CACHE_TIMEOUT
          value: "300"
        - name: JWT_OIDC_JWKS_URI
          value: "https://kc.formflow.click/auth/realms/forms-flow-ai/protocol/openid-connect/certs"
        - name: JWT_OIDC_WELL_KNOWN_CONFIG
          value: "https://kc.formflow.click/auth/realms/forms-flow-ai/.well-known/openid-configuration"
        - name: KEYCLOAK_URL
          value: "https://kc.formflow.click/"
        - name: WEB_API_BASE_URL
          value: "forms-flow-webapi"  ---> k8s forms-flow api SVC
        - name: KEYCLOAK_URL_REALM
          value: "forms-flow-ai"
        - name: FORMSFLOW_API_CORS_ORIGINS
          value: "*"
        - name:  INSIGHT_API_URL
          value:  "forms-flow-analytics" ---> k8s analytics SVC
```

**forms-flow-bpm/templates/deploymentconfig.yaml**

```
 - env:
        - name: APP_SECURITY_ORIGIN
          value: "*"
        - name: CAMUNDA_DATABASE_NAME
          value: "formsflow-bpm"
        - name: CAMUNDA_DATABASE_SERVICE_NAME
          value: "camunda-postgresql"
        - name: CAMUNDA_JDBC_DRIVER
          value: "org.postgresql.Driver"
        - name: CAMUNDA_JDBC_USER
          value: "admin"
        - name: CAMUNDA_JDBC_URL
          value: "jdbc:postgresql://camunda-postgresql:5432/formsflow-bpm"
        - name: WAIT_FOR
          value: camunda-postgresql:5432
        - name: CAMUNDA_JDBC_PASSWORD
          value: <password>
        - name: KEYCLOAK_URL
          value: "https://kc.formflow.click"
        - name: KEYCLOAK_URL_REALM
          value: forms-flow-ai
        - name: KEYCLOAK_CLIENTID
          value: forms-flow-bpm
        - name: MAIL_CONFIG
          value: /app/mail-config.properties
        - name: CAMUNDA_FORMBUILDER_PIPELINE_USERNAME
          value: "{{ .Values.camunda_formbuilder_pipeline_username }}"
        - name: CAMUNDA_FORMBUILDER_PIPELINE_PASSWORD
          value: "{{ .Values.camunda_formbuilder_pipeline_password }}"
        - name: CAMUNDA_FORMBUILDER_PIPELINE_BPM_URL
          value: forms-flow-ai
        - name: CAMUNDA_ANALYTICS_DATABASE_SERVICE_NAME
          value: "{{ .Values.analytics_db_resource_name }}"
        - name: CAMUNDA_ANALYTICS_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              key: DATABASE_NAME
              name: "{{ .Values.analytics_db_resource_name }}"
        - name: CAMUNDA_BPM_HISTORY_LEVEL
          value: none
        - name: CAMUNDA_AUTHORIZATION_FLAG
          value: "true"
        - name: CAMUNDA_APP_ROOT_LOG_FLAG
          value: "{{ .Values.camunda_app_root_log_flag }}"
        - name: FORMSFLOW_API_URL
          value: "forms-flow-webapi"
        - name: FORMIO_URL
          value: "forms-flow-forms" --> k8s FormIO  SVC
        - name: FORMIO_ROOT_EMAIL
          value: "admin@formflow.click"
        - name: FORMIO_ROOT_PASSWORD
          value:  <password>
        - name: WEBSOCKET_ENCRYPT_KEY
          value: <key>
        - name: WEBSOCKET_MESSAGE_TYPE
          value: TASK_EVENT
        - name: WEBSOCKET_SECURITY_ORIGIN
          value: "forms-flow-web"  ---> k8s Form-flow web SVC
```
**/forms-flow-forms/templates/deploymentconfig.yaml**
```
       - name: DEBUG
          value: formio:*
        - name: NODE_CONFIG
          value: "{\"mongo\":\"mongodb://admin:<password>@mongodb:27017/formio?authSource=admin\"}"
        - name: ROOT_EMAIL
          value: admin@formflow.click
        - name: ROOT_PASSWORD
          value: <password>
        - name: FORMIO_DOMAIN
          value: "https://formflow.formflow.click"
        - name: FORMIO_JWT_SECRET
          value: <secret>

```
